// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: frame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from frame.proto</summary>
  public static partial class FrameReflection {

    #region Descriptor
    /// <summary>File descriptor for frame.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FrameReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtmcmFtZS5wcm90bxIFcHJvdG8iJwoUUmVxdWVzdEdhbWVNYW5hZ2VSZXES",
            "DwoHQ29tbWFuZBgBIAMoCSIoChNSZXF1ZXN0SGVhcnRCZWF0UmVxEhEKCVRp",
            "bWVTdGFtcBgBIAEoCSIoChNSZXF1ZXN0SGVhcnRCZWF0UnNwEhEKCVRpbWVT",
            "dGFtcBgBIAEoCSI5CgdSZXF1ZXN0EgwKBENvZGUYASABKAUSDAoERGF0YRgC",
            "IAEoDBISCgpDbGllbnREYXRhGAMgASgJIl8KCFJlc3BvbnNlEgwKBENvZGUY",
            "ASABKAUSDwoHTWVzc2FnZRgCIAEoCRIMCgREYXRhGAMgASgMEhIKClJlc3Vs",
            "dGNvZGUYBCABKAUSEgoKQ2xpZW50RGF0YRgFIAEoCSrpCQoLUmVxdWVzdENv",
            "ZGUSEwoPUmVxdWVzdENvZGVaZXJvEAASFAoQUmVxdWVzdEhlYXJ0QmVhdBBk",
            "EhYKEVJlcXVlc3RHYW1lTWFuYWdlEOgHEhYKEVJlcXVlc3RDcmVhdGVSb2xl",
            "EOkHEhYKEVJlcXVlc3RVcGRhdGVSb2xlEOoHEhMKDlJlcXVlc3RHZXRSb2xl",
            "EOsHEh4KGVNlcnZlclRvQ2xpZW50Z2V0Um9sZUluZm8Q7AcSGAoTUmVxdWVz",
            "dEZpbmRyYW5zcG9ydBDNCBIYChNSZXF1ZXN0QWRkVHJhbnNwb3J0EM4IEhcK",
            "ElJlcXVlc3RSZWZyZXNoRGljZRDPCBIUCg9SZXF1ZXN0TW92ZVJvbGUQsQkS",
            "FAoPUmVxdWVzdENpdHlsaXN0ENEPEhQKD1JlcXVlc3RDaXR5aW5mbxDSDxIX",
            "ChJSZXF1ZXN0Q2l0eU1hcERhdGEQ0w8SHgoZUmVxdWVzdExpbmVvZlVzZXJQ",
            "b3NpdGlvbhDWDxIdChhSZXF1ZXN0R2l2ZVVwUmVjbGFtYXRpb24Q3Q8SFwoS",
            "UmVxdWVzdFJlY2xhbWF0aW9uEN4PEhsKFlJlcXVlc3RSZWNsYW1hdGlvblN1",
            "Y2MQ3w8SEgoNUmVxdWVzdEdvV2FsaxDaDxIWChFSZXF1ZXN0V2Fsa1Zlcmlm",
            "eRDkDxIZChRSZXF1ZXN0V2Fsa1ZlcmlmeUVychDlDxIaChVSZXF1ZXN0V2Fs",
            "a1ZlcmlmeVN1Y2MQ5g8SEwoOUmVxdWVzdFdhbGtXYXkQ7g8SFwoSUmVxdWVz",
            "dEFkZEJ1aWxkaW5nELkXEhgKE1JlcXVlc3RGaW5kQnVpbGRpbmcQuhcSFwoS",
            "UmVxdWVzdEdldEJ1aWxkaW5nELsXEhoKFVJlcXVlc3RJbnZlc3RCdWlsZGlu",
            "ZxC8FxIaChVSZXF1ZXN0Q2hhbmdlQnVpbGRpbmcQvRcSGwoWUmVxdWVzdENv",
            "bnN1bWVCdWlsZGluZxC+FxIlCiBSZXF1ZXN0SW52ZXN0bWVudFJhbmtpbmdC",
            "dWlsZGluZxC/FxIcChdSZXF1ZXN0RmluZEJ1aWxkaW5nV29yaxDAFxIaChVS",
            "ZXF1ZXN0V29ya0luQnVpbGRpbmcQwRcSHgoZUmVxdWVzdEluaXRTeXN0ZW1C",
            "dWlsZGluZxDCFxIcChdSZXF1ZXN0SG9zcGl0YWxCdWlsZGluZxDDFxIaChVS",
            "ZXF1ZXN0UG9saWNlQnVpbGRpbmcQxBcSHAoXUmVxdWVzdEJ1aWxkaW5nSW5p",
            "dFN1Y2MQzRcSGwoWUmVxdWVzdEJ1aWxkaW5nVXBncmFkZRDOFxIeChlSZXF1",
            "ZXN0QnVpbGRpbmdDaGFuZ2VUeXBlEM8XEhwKF1JlcXVlc3RCdWlsZGluZ1Vz",
            "ZXJXb3JrENAXEhYKEVJlcXVlc3RXYWxsZXRJbmZvEKEfEhUKEFJlcXVlc3RS",
            "YXJlY0luZm8Qoh8SGAoTUmVxdWVzdENyaW1pbmFsSW5mbxCIJxIWChFSZXF1",
            "ZXN0UG9saWNlV2FsaxCJJxIYChNSZXF1ZXN0UG9saWNlVmVyaWZ5EIsnEhsK",
            "FlJlcXVlc3RQb2xpY2VPcGVyYXRpb24QiicSGgoVUmVxdWVzdEVuZE9mRGV0",
            "ZW50aW9uEIwnEhQKDlJlcXVlc3RDb2RlTWF4ENCGAyo5CgxSZXNwb25zZUNv",
            "ZGUSFAoQUmVzcG9uc2VDb2RlWmVybxAAEhMKDlJlc3BvbnNlQ29kZU9rEMgB",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.RequestCode), typeof(global::Proto.ResponseCode), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.RequestGameManageReq), global::Proto.RequestGameManageReq.Parser, new[]{ "Command" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.RequestHeartBeatReq), global::Proto.RequestHeartBeatReq.Parser, new[]{ "TimeStamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.RequestHeartBeatRsp), global::Proto.RequestHeartBeatRsp.Parser, new[]{ "TimeStamp" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Request), global::Proto.Request.Parser, new[]{ "Code", "Data", "ClientData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Response), global::Proto.Response.Parser, new[]{ "Code", "Message", "Data", "Resultcode", "ClientData" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///RequestCode 消息类型
  /// </summary>
  public enum RequestCode {
    [pbr::OriginalName("RequestCodeZero")] Zero = 0,
    /// <summary>
    ///心跳
    /// </summary>
    [pbr::OriginalName("RequestHeartBeat")] RequestHeartBeat = 100,
    /// <summary>
    /// 执行gm指令
    /// </summary>
    [pbr::OriginalName("RequestGameManage")] RequestGameManage = 1000,
    /// <summary>
    ///创建角色
    /// </summary>
    [pbr::OriginalName("RequestCreateRole")] RequestCreateRole = 1001,
    /// <summary>
    ///修改角色
    /// </summary>
    [pbr::OriginalName("RequestUpdateRole")] RequestUpdateRole = 1002,
    /// <summary>
    ///查看角色 请求无需参数
    /// </summary>
    [pbr::OriginalName("RequestGetRole")] RequestGetRole = 1003,
    /// <summary>
    ///推送角色变更
    /// </summary>
    [pbr::OriginalName("ServerToClientgetRoleInfo")] ServerToClientgetRoleInfo = 1004,
    /// <summary>
    ///查询交通工具 请求无需参数
    /// </summary>
    [pbr::OriginalName("RequestFindransport")] RequestFindransport = 1101,
    /// <summary>
    ///购买交通工具
    /// </summary>
    [pbr::OriginalName("RequestAddTransport")] RequestAddTransport = 1102,
    /// <summary>
    ///刷新交通工具骰子
    /// </summary>
    [pbr::OriginalName("RequestRefreshDice")] RequestRefreshDice = 1103,
    /// <summary>
    ///移动
    /// </summary>
    [pbr::OriginalName("RequestMoveRole")] RequestMoveRole = 1201,
    /// <summary>
    ///查询城市列表
    /// </summary>
    [pbr::OriginalName("RequestCitylist")] RequestCitylist = 2001,
    /// <summary>
    ///查询城市基础信息
    /// </summary>
    [pbr::OriginalName("RequestCityinfo")] RequestCityinfo = 2002,
    /// <summary>
    ///查询城市基础信息
    /// </summary>
    [pbr::OriginalName("RequestCityMapData")] RequestCityMapData = 2003,
    /// <summary>
    ///该线上的其他玩家位置
    /// </summary>
    [pbr::OriginalName("RequestLineofUserPosition")] RequestLineofUserPosition = 2006,
    /// <summary>
    ///放弃此回合开垦
    /// </summary>
    [pbr::OriginalName("RequestGiveUpReclamation")] RequestGiveUpReclamation = 2013,
    /// <summary>
    ///购买开垦地块请求
    /// </summary>
    [pbr::OriginalName("RequestReclamation")] RequestReclamation = 2014,
    /// <summary>
    ///开垦地块成功
    /// </summary>
    [pbr::OriginalName("RequestReclamationSucc")] RequestReclamationSucc = 2015,
    /// <summary>
    ///玩家行走(走一格发一格)
    /// </summary>
    [pbr::OriginalName("RequestGoWalk")] RequestGoWalk = 2010,
    /// <summary>
    ///玩家行走(验证后推送)
    /// </summary>
    [pbr::OriginalName("RequestWalkVerify")] RequestWalkVerify = 2020,
    /// <summary>
    ///玩家行走错误
    /// </summary>
    [pbr::OriginalName("RequestWalkVerifyErr")] RequestWalkVerifyErr = 2021,
    /// <summary>
    ///玩家行走成功
    /// </summary>
    [pbr::OriginalName("RequestWalkVerifySucc")] RequestWalkVerifySucc = 2022,
    /// <summary>
    ///重新获取玩家路线
    /// </summary>
    [pbr::OriginalName("RequestWalkWay")] RequestWalkWay = 2030,
    /// <summary>
    ///新建建筑
    /// </summary>
    [pbr::OriginalName("RequestAddBuilding")] RequestAddBuilding = 3001,
    /// <summary>
    ///获取城市建筑基础信息
    /// </summary>
    [pbr::OriginalName("RequestFindBuilding")] RequestFindBuilding = 3002,
    /// <summary>
    ///获取某个建筑详细信息
    /// </summary>
    [pbr::OriginalName("RequestGetBuilding")] RequestGetBuilding = 3003,
    /// <summary>
    ///建筑投资
    /// </summary>
    [pbr::OriginalName("RequestInvestBuilding")] RequestInvestBuilding = 3004,
    /// <summary>
    ///建筑更改
    /// </summary>
    [pbr::OriginalName("RequestChangeBuilding")] RequestChangeBuilding = 3005,
    /// <summary>
    ///建筑消费
    /// </summary>
    [pbr::OriginalName("RequestConsumeBuilding")] RequestConsumeBuilding = 3006,
    /// <summary>
    ///查看投资排行榜
    /// </summary>
    [pbr::OriginalName("RequestInvestmentRankingBuilding")] RequestInvestmentRankingBuilding = 3007,
    /// <summary>
    ///查看建筑打工位
    /// </summary>
    [pbr::OriginalName("RequestFindBuildingWork")] RequestFindBuildingWork = 3008,
    /// <summary>
    ///建筑打工
    /// </summary>
    [pbr::OriginalName("RequestWorkInBuilding")] RequestWorkInBuilding = 3009,
    /// <summary>
    ///开拓城市初始化模板中的系统建筑信息
    /// </summary>
    [pbr::OriginalName("RequestInitSystemBuilding")] RequestInitSystemBuilding = 3010,
    /// <summary>
    /// 医院
    /// </summary>
    [pbr::OriginalName("RequestHospitalBuilding")] RequestHospitalBuilding = 3011,
    /// <summary>
    ///警察局
    /// </summary>
    [pbr::OriginalName("RequestPoliceBuilding")] RequestPoliceBuilding = 3012,
    /// <summary>
    ///添加建筑成功
    /// </summary>
    [pbr::OriginalName("RequestBuildingInitSucc")] RequestBuildingInitSucc = 3021,
    /// <summary>
    ///建筑升级
    /// </summary>
    [pbr::OriginalName("RequestBuildingUpgrade")] RequestBuildingUpgrade = 3022,
    /// <summary>
    ///建筑更改类型后广播
    /// </summary>
    [pbr::OriginalName("RequestBuildingChangeType")] RequestBuildingChangeType = 3023,
    /// <summary>
    ///玩家打工变更广播
    /// </summary>
    [pbr::OriginalName("RequestBuildingUserWork")] RequestBuildingUserWork = 3024,
    /// <summary>
    ///钱包信息
    /// </summary>
    [pbr::OriginalName("RequestWalletInfo")] RequestWalletInfo = 4001,
    /// <summary>
    ///请求稀土信息
    /// </summary>
    [pbr::OriginalName("RequestRarecInfo")] RequestRarecInfo = 4002,
    /// <summary>
    /// 警察局信息
    /// </summary>
    [pbr::OriginalName("RequestCriminalInfo")] RequestCriminalInfo = 5000,
    /// <summary>
    ///警察行走
    /// </summary>
    [pbr::OriginalName("RequestPoliceWalk")] RequestPoliceWalk = 5001,
    /// <summary>
    ///警察行走验证
    /// </summary>
    [pbr::OriginalName("RequestPoliceVerify")] RequestPoliceVerify = 5003,
    /// <summary>
    ///新增减少警察
    /// </summary>
    [pbr::OriginalName("RequestPoliceOperation")] RequestPoliceOperation = 5002,
    /// <summary>
    ///通知拘留结束
    /// </summary>
    [pbr::OriginalName("RequestEndOfDetention")] RequestEndOfDetention = 5004,
    /// <summary>
    ///不要大于这个
    /// </summary>
    [pbr::OriginalName("RequestCodeMax")] Max = 50000,
  }

  /// <summary>
  ///ResponseCode 消息类型
  /// </summary>
  public enum ResponseCode {
    [pbr::OriginalName("ResponseCodeZero")] Zero = 0,
    [pbr::OriginalName("ResponseCodeOk")] Ok = 200,
  }

  #endregion

  #region Messages
  /// <summary>
  /// GM请求
  /// </summary>
  public sealed partial class RequestGameManageReq : pb::IMessage<RequestGameManageReq> {
    private static readonly pb::MessageParser<RequestGameManageReq> _parser = new pb::MessageParser<RequestGameManageReq>(() => new RequestGameManageReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestGameManageReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.FrameReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestGameManageReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestGameManageReq(RequestGameManageReq other) : this() {
      command_ = other.command_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestGameManageReq Clone() {
      return new RequestGameManageReq(this);
    }

    /// <summary>Field number for the "Command" field.</summary>
    public const int CommandFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_command_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> command_ = new pbc::RepeatedField<string>();
    /// <summary>
    ///指令
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Command {
      get { return command_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestGameManageReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestGameManageReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!command_.Equals(other.command_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= command_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      command_.WriteTo(output, _repeated_command_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += command_.CalculateSize(_repeated_command_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestGameManageReq other) {
      if (other == null) {
        return;
      }
      command_.Add(other.command_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            command_.AddEntriesFrom(input, _repeated_command_codec);
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 心跳包
  /// </summary>
  public sealed partial class RequestHeartBeatReq : pb::IMessage<RequestHeartBeatReq> {
    private static readonly pb::MessageParser<RequestHeartBeatReq> _parser = new pb::MessageParser<RequestHeartBeatReq>(() => new RequestHeartBeatReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestHeartBeatReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.FrameReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeartBeatReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeartBeatReq(RequestHeartBeatReq other) : this() {
      timeStamp_ = other.timeStamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeartBeatReq Clone() {
      return new RequestHeartBeatReq(this);
    }

    /// <summary>Field number for the "TimeStamp" field.</summary>
    public const int TimeStampFieldNumber = 1;
    private string timeStamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestHeartBeatReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestHeartBeatReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimeStamp != other.TimeStamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TimeStamp.Length != 0) hash ^= TimeStamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TimeStamp.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TimeStamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TimeStamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestHeartBeatReq other) {
      if (other == null) {
        return;
      }
      if (other.TimeStamp.Length != 0) {
        TimeStamp = other.TimeStamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TimeStamp = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 心跳回复
  /// </summary>
  public sealed partial class RequestHeartBeatRsp : pb::IMessage<RequestHeartBeatRsp> {
    private static readonly pb::MessageParser<RequestHeartBeatRsp> _parser = new pb::MessageParser<RequestHeartBeatRsp>(() => new RequestHeartBeatRsp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RequestHeartBeatRsp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.FrameReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeartBeatRsp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeartBeatRsp(RequestHeartBeatRsp other) : this() {
      timeStamp_ = other.timeStamp_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RequestHeartBeatRsp Clone() {
      return new RequestHeartBeatRsp(this);
    }

    /// <summary>Field number for the "TimeStamp" field.</summary>
    public const int TimeStampFieldNumber = 1;
    private string timeStamp_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string TimeStamp {
      get { return timeStamp_; }
      set {
        timeStamp_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RequestHeartBeatRsp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RequestHeartBeatRsp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimeStamp != other.TimeStamp) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TimeStamp.Length != 0) hash ^= TimeStamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TimeStamp.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TimeStamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TimeStamp.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TimeStamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RequestHeartBeatRsp other) {
      if (other == null) {
        return;
      }
      if (other.TimeStamp.Length != 0) {
        TimeStamp = other.TimeStamp;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TimeStamp = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///Request 请求
  /// </summary>
  public sealed partial class Request : pb::IMessage<Request> {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.FrameReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request(Request other) : this() {
      code_ = other.code_;
      data_ = other.data_;
      clientData_ = other.clientData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "ClientData" field.</summary>
    public const int ClientDataFieldNumber = 3;
    private string clientData_ = "";
    /// <summary>
    ///客户端内部数据(不解析)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientData {
      get { return clientData_; }
      set {
        clientData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Data != other.Data) return false;
      if (ClientData != other.ClientData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (ClientData.Length != 0) hash ^= ClientData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
      if (ClientData.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ClientData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (ClientData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.ClientData.Length != 0) {
        ClientData = other.ClientData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
          case 26: {
            ClientData = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  ///Response 返回值
  /// </summary>
  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.FrameReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      code_ = other.code_;
      message_ = other.message_;
      data_ = other.data_;
      resultcode_ = other.resultcode_;
      clientData_ = other.clientData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private int code_;
    /// <summary>
    ///执行操作码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "Message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    ///运行结果消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    ///运行结果数据
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Resultcode" field.</summary>
    public const int ResultcodeFieldNumber = 4;
    private int resultcode_;
    /// <summary>
    ///运行结果code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Resultcode {
      get { return resultcode_; }
      set {
        resultcode_ = value;
      }
    }

    /// <summary>Field number for the "ClientData" field.</summary>
    public const int ClientDataFieldNumber = 5;
    private string clientData_ = "";
    /// <summary>
    ///客户端内部数据(不解析)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ClientData {
      get { return clientData_; }
      set {
        clientData_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Message != other.Message) return false;
      if (Data != other.Data) return false;
      if (Resultcode != other.Resultcode) return false;
      if (ClientData != other.ClientData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != 0) hash ^= Code.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (Resultcode != 0) hash ^= Resultcode.GetHashCode();
      if (ClientData.Length != 0) hash ^= ClientData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Code);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (Resultcode != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Resultcode);
      }
      if (ClientData.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ClientData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Code);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (Resultcode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Resultcode);
      }
      if (ClientData.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ClientData);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Code != 0) {
        Code = other.Code;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      if (other.Resultcode != 0) {
        Resultcode = other.Resultcode;
      }
      if (other.ClientData.Length != 0) {
        ClientData = other.ClientData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = input.ReadInt32();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 26: {
            Data = input.ReadBytes();
            break;
          }
          case 32: {
            Resultcode = input.ReadInt32();
            break;
          }
          case 42: {
            ClientData = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
